[sleeper]
league_id = ""
poll_seconds = 5

[draft]
rounds = 15
teams = 12

[starters]
QB = 1
RB = 2
WR = 3
TE = 1
K = 1
DST = 1

[scoring]
ppr = 1.0
w_proj = 0.65
w_vbd = 0.35
w_ecr_delta = 0.12
w_injury_pen = 0.06
w_volatility = 0.05

[user_profile]
sleeper_username = "Fallon3D"
user_slot = 0

[strategy]
default_strategy = "Hero RB + WR Flood (optional early TE)"
elite_te_value = 78.0
hero_rb_value = 85.0
kd_only_last_round = true
